# Copyright 2016-2018 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/

install:
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - cd ..
  - git clone -b %BOOST_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% tools\boostdep\
  - 7za -otools\boostdep\test x tools\boostdep\test\utf8-test.zip
  - dir tools\boostdep\test
  - python tools/boostdep/depinst/depinst.py ../tools/boostdep
  - cmd /c bootstrap
  - b2 -d0 headers

build: off

test_script:
  - b2 -j3 tools/boostdep/test toolset=msvc-9.0,msvc-10.0,msvc-11.0,msvc-14.0
